application: entreprises
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /template
  static_dir: template
- url: /views
  static_dir: views
- url: /.*
  script: entreprises.py