application: entreprises
<<<<<<< HEAD
version: 2
=======
version: 1
>>>>>>> origin/master
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: entreprises.py