application: algenreprise
version: 3
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /.*
  script: entreprises.py